#!/usr/bin/python3

import sys
import webbrowser
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("query", help="keyword to be googled ; enter URL if using exact search (-e flag)")
parser.add_argument("-e","--exact", help="search for an exact URL", action="store_true")
parser.add_argument("-y", "--youtube", help="search youtube for <keyword>", action="store_true")
args = parser.parse_args()

if args.exact and args.youtube:
    print("Conflicting arguments...")

elif args.exact:
    print("exact search is enabled...")
    print(f"RUNNING EXACT SEARCH FOR: {args.query}")
    webbrowser.open(str(args.query))
else:
    params = str(args.query)
    params = params.replace(" ", "+")
    if args.youtube:
        print("Youtube search is enabled...")
        print(f"RUNNING YOUTUBE SEARCH FOR: {args.query}")
        webbrowser.open("https://www.youtube.com/results?search_query={}".format(params))
    elif args.exact != True:
        print("exact search is disabled...")
        print(f"RUNNING SEARCH FOR: {args.query}")
        webbrowser.open("https://www.google.com/search?q={}&oq={}&aqs=chrome..69i57j46j0l6.2572j0j7&sourceid=chrome&ie=UTF-8".format(params, params))
